version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: decskill
      POSTGRES_PASSWORD: decskill
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:

